plan.post.requests:
  - post-request:
      component: helloworld
      method: POST
      path: /post-hello
      protocol: http
      params:                                     #Request params '- name: value'
        - name: test-value
      body: '{
              "data": "data",
              "number": 1234,
              "nextData": "nextData"
             }'
  - post-request-header:
      component: helloworld
      method: POST
      path: /post-hello-header
      protocol: http
      headers:
       - headerName: headerValue
      params:                                     #Request params '- name: value'
        - name: test-post-param-value
      body: '{
              "data": "data",
              "number": 1234,
              "nextData": "nextData"
             }'