duration: 10M30S   #Duration in hHmMsS
stages: 5

# Monitoring config example

#monitoring:
#  metricsURI: "http://address:port"        #URI to metrics resource
#  metrics:
#    success_percentage:                    # internal name of metric
#      tag: "SUCCESS_PERCENTAGE_WINDOWED"   # tag to query metric
#      min: 95.0                            # boundary values of metric; min, max or both
#    99_percentile:
#      tag: "GENERAL_TIMER_seconds{quantile=\"0.95\",}"
#      max: #{6.0 / 1000}


rules:
  helloworld-istio-network:
    type: network
    components:
      - helloworld-springboot-istio
    params:
      # Each parameter is a single value or a list of values. If a list of values is
      # specified, then the number of values must be equal to the number of stages.
      http-error:
        code: 503
        percentage: [1, 3, 5, 10, 20]

  kill-helloworld:
    type: pod

    # Modes:
    #   * fixed: affect specified number of pods
    #   * percent: affect % of pods, number to affect is calculated as follows: floor(num_pods * severity / 100)
    mode: fixed
    components:
      - helloworld-springboot
    params:
      severity: [1, 1, 1, 2, 2]
      timeout: 15