helloworld:
  components:
    - helloworld-springboot

kubernetes:
  components:
    - cloud-service-example

helloworld-istio:
  components:
    - helloworld-springboot-istio

jmeter:
  components:
    - loadtest-simple-example