helloworld:
  components:
    - helloworld-springboot

kubernetes:
  components:
    - cloud-service-example

helloworld-istio:
  components:
    - helloworld-springboot-istio

demo:
  components:
    - demo-backend
    - demo-frontend
    - chaos

jmeter:
  components:
    - loadtest-simple-example
