helloworld:
  components:
    - helloworld-springboot

kubernetes:
  components:
    - cloud-service-example

helloworld-istio:
  components:
    - helloworld-springboot-istio

#chaos:
#  components:
#    - chaos

demo:
  components:
    - demo-backend
    - demo-frontend
    - chaos