helloworld:
  components:
    - helloworld-springboot
    - fakejo

#helloworld-istio:
#  components:
#    - helloworld-springboot-istio
#
#demo:
#  components:
#    - chaos
#
#jmeter:
#  components:
#    - loadtest-simple-example
