helloworld:
  components:
    - helloworld-springboot

helloworld-istio:
  components:
    - helloworld-springboot-istio

simpleweb:
  components:
    - simpleweb

jmeter:
  components:
    - openshift-jmeter