kind: Service
apiVersion: v1
metadata:
  name: ${this@name}-service
  labels:
    application: ${this@name}
    configHash: <CONFIG_HASH>
spec:
  selector:
    application: ${this@name}
  ports:
    - port: ${this@server.port}
      protocol: TCP
      targetPort: ${this@server.port}
      name: http-${this@server.port}