requests:
  - hello-request:
      component: helloworld-springboot            #Name of component or 'domain: target system domain'
      method: GET
      path: /hello
      protocol: http
      headers:
        - headerName: headerValue
      params:                                     #Request params '- name: value'
        - paramName: test-param-value
        - nextParamName: next-test-param-value
  - next-hello-request:
      component: helloworld-springboot
      method: GET
      path: /next-hello
      protocol: http
      params:
        - name: test-param-value
  - post-request:
      component: helloworld-springboot
      method: POST
      path: /post-hello
      protocol: http
      body: '{
              	"data": "data",
              	"number": 1234,
              	"nextData": "nextData"
              }'
  - post-request-header:
      component: helloworld-springboot
      method: POST
      path: /post-hello-header
      protocol: http
      headers:
        - headerName: headerValue
      body: '{
              	"data": "data",
              	"number": 1234,
              	"nextData": "nextData"
              }'
numberOfThreads: 10
rampUpPeriod: 1
duration: 20