requests:
  - hello-request:
      component: helloworld-springboot
      method: GET
      path: /hello
      protocol: http
      params:
        - paramName: test-param-value
        - nextParamName: next-test-param-value
  - next-hello-request:
      component: helloworld-springboot
      method: GET
      path: /next-hello
      protocol: http
number_of_threads: 30
ramp_up_period: 1
duration: 20