plan.post-test:
 requests:
   - post-request:
       component: helloworld-springboot
       method: POST
       path: /post-hello
       protocol: http
       body: '{
               	"data": "data",
               	"number": 1234,
               	"nextData": "nextData"
               }'
   - post-request-header:
       component: helloworld-springboot
       method: POST
       path: /post-hello-header
       protocol: http
       headers:
         - headerName: headerValue
       body: '{
               	"data": "data",
               	"number": 1234,
               	"nextData": "nextData"
               }'
 numberOfThreads: 2
 rampUpPeriod: 1
 duration: 4