#include loadtest-simple-example-requests
#include metrics

numberOfThreads: 10             #users on one slave node
rampUpPeriod: 1
duration: 10

peak-load-test:
  step: 25                      #users on one slave node
  errors: 60                    #percent of errors
  average-response-time: 1500   #value in mc