kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: <CONFIG_NAME>
  labels:
    application: <CONFIG_NAME>
spec:
  selector:
    application: <CONFIG_NAME>
  template:
    metadata:
      labels:
        application: <CONFIG_NAME>
      annotations:
        sidecar.istio.io/inject: '${this@istioInject}'
    spec:
      containers:
        - image: ${this@image-master.url}
          volumeMounts:
            - name: jmeter-props
              mountPath: /app/resources
          env:
            - name: SLAVE_HOSTS
              value: <SLAVE_HOSTS>
            - name: PATH_TO_JMETERPLAN
              value: /app/resources/testplan.jmx
          imagePullPolicy: Always
          name: <CONFIG_NAME>
          ports:
            - containerPort: ${this@master.port}
              protocol: TCP
          resources:
            requests:
              cpu: ${this@requests.cpu}
              memory: ${this@requests.memory}
            limits:
              cpu: ${this@limits.cpu}
              memory: ${this@limits.memory}
      volumes:
        - name: jmeter-props
          configMap:
            name: jmeter-test-template
      restartPolicy: Always
  triggers:
    - type: ConfigChange
  replicas: 1
  strategy:
    type: Rolling