kind: Template
apiVersion: v1
metadata:
  name: "${CONFIG_NAME}"
labels:
  template: "${CONFIG_NAME}"
  app: "${CONFIG_NAME}"
objects:
  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      name: "${CONFIG_NAME}.${this@version}"
      labels:
        application: "${CONFIG_NAME}"
        projectVersion: latest
        configVersion: custom
    spec:
      template:
        metadata:
          labels:
            application: "${CONFIG_NAME}"
            projectVersion: latest
            configVersion: custom
          annotations:
            sidecar.istio.io/inject: 'true'
        spec:
          containers:
            - image: registry.hub.docker.com/slav9n4ik/jmeter-slave:latest
              imagePullPolicy: Always
              name: "${CONFIG_NAME}"
              ports:
                - containerPort: 1099
                  protocol: TCP
                - containerPort: 50000
                  protocol: TCP
              resources:
                requests:
                  cpu: 0.25
                  memory: 256M
                limits:
                  cpu: 0.25
                  memory: 512M
          restartPolicy: Always
      triggers:
        - type: ConfigChange
      replicas: 1
      strategy:
        type: Rolling

  - kind: Service
    apiVersion: v1
    metadata:
      name: "${CONFIG_NAME}"
      labels:
        application: "${CONFIG_NAME}"
    spec:
      selector:
        application: "${CONFIG_NAME}"
      clusterIP: None
      ports:
        - port: 1099
          name: first
          targetPort: 1099
        - port: 50000
          name: second
          targetPort: 50000

#  - kind: Route
#    apiVersion: v1
#    metadata:
#      name: "${CONFIG_NAME}"
#      labels:
#        application: "${CONFIG_NAME}"
#    spec:
#      to:
#        kind: Service
#        name: "${CONFIG_NAME}"
#        weight: 100

parameters:
  - name: CONFIG_NAME
    description: "Project name"
    required: true
    value: #SLAVE_PROJECT_NAME#