kind: Service
apiVersion: v1
metadata:
  name: ${this@cluster.service.name}
  labels:
    application: ${this@name}
spec:
  selector:
    application: ${this@name}
  ports:
    - port: ${this@server.port}
      protocol: TCP
      targetPort: ${this@server.port}
      name: http-${this@server.port}